{{- if and (not .Values.secret.existingSecretName) .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "java-k8s.secretName" . }}
  labels:
    {{- include "java-k8s.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.data }}
    {{- range $setting, $option := .Values.secret.data }}
    {{ $setting | quote }}: {{ $option | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- end }}