{{- if and (not .Values.env.existingSecret ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "java-k8s.fullname" . }}
  labels:
    {{- include "java-k8s.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.env.secret }}
  {{- if not (empty $value) }}
    {{ $name | quote }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
