{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-k8s.fullname" . }}
  labels:
    {{- include "java-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "java-k8s.selectorLabels" . | nindent 4 }}
{{- end }}
